### ISSUE TITLE
kn workflow create: unknown flag: --extension

### ISSUE THREAD

**Issue by gpando-mercadona** [kiegroup/kogito-docs#378]
In https://sonataflow.org/serverlessworkflow/latest/getting-started/create-your-first-workflow-service.html#proc-boostrapping-the-project

`kn workflow create \`
 ` --name serverless-workflow-hello-world \`
 ` --extension quarkus-jsonp,quarkus-smallrye-openapi \`
 ` --quarkus-platform-group-id=io.quarkus.platform \  ` 
 ` --quarkus-version=2.16.7.Final`

error : unknown flag: --extension

**Comment by ederign** [comment]
@gpando-mercadona since two releases ago, we moved all quarkus commands to *quarkus* sub command.

So you should use:

kn workflow quarkus create \
 --name serverless-workflow-hello-world \
 --extension quarkus-jsonp,quarkus-smallrye-openapi \
--quarkus-platform-group-id=io.quarkus.platform \ 
 --quarkus-version=2.16.7.Final
 
 
 Apologies for the outdated docs. We just released 0.31.0 yesterday (please use this version) and we will start to work on docs next week.

**Comment by gpando-mercadona** [comment]
Thanks
